service:
  name: redditify-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          method: get
          path: hello

custom:
  serverless-offline:
    port: 4000
